[tool.poetry]
name = "color-trace"
version = "1.0.2"
description = ""
authors = ["Haujet <1292756898@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
lxml = "^5.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
